name: GPU CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
      - v*
  pull_request:
    branches: [ main ]

jobs:

  pull:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
       fetch-depth: 0

  build:
    runs-on: self-hosted
    container: 
      image: nvcr.io/nvstaging/merlin/merlin_ci_runner:latest
      volumes:
        - ${{ github.workspace }}:/dataloader
      options: --gpus all --ipc=host --privileged
    steps:
    - name: Install
      run: |
        cd /dataloader; pip install . --no-deps
    - name: Test 
      run: |
        cd /dataloader; pytest tests/unit

